#ddev-generated
services:
  lucee:
    container_name: ddev-${DDEV_SITENAME}-lucee
    image: lucee/lucee:6.1
    restart: "no"
    ports:
      - "8888:8888"  # Tomcat/Lucee
    environment:
      - LUCEE_ADMIN_PASSWORD=admin
      - LUCEE_JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - type: bind
        consistency: cached
        source: ${DDEV_APPROOT}/${DDEV_DOCROOT}
        target: /var/www
      - "./lucee/web:/opt/lucee/web:rw"
      - "./lucee/server:/opt/lucee/server/lucee-server/context:rw"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-type: lucee
      http_expose: "8888:8888"
      https_expose: "8888:8888"

networks:
  default:
    name: ddev_default
    external: true