#ddev-generated
services:
  lucee:
    container_name: ddev-${DDEV_SITENAME}-lucee
    image: lucee/lucee:6.1
    restart: "no"
    ports:
      - "8888:8888"  # Tomcat/Lucee
    environment:
      - LUCEE_ADMIN_PASSWORD=admin
      - LUCEE_JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - type: bind
        consistency: cached
        source: ${DDEV_APPROOT}/${DDEV_DOCROOT}
        target: /var/www
      - "./config/lucee:/opt/lucee/web:rw"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.describe.lucee: |
        Server Admin: https://${DDEV_SITENAME}.ddev.site:8888/lucee/admin/server.cfm
        Web Admin: https://${DDEV_SITENAME}.ddev.site:8888/lucee/admin/web.cfm
        Password: admin

networks:
  default:
    name: ddev_default
    external: true