name: tests
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches: [ main ]

  schedule:
  - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This is required for "gautamkrishnar/keepalive-workflow", see "ddev/github-action-add-on-test"
permissions:
  actions: write

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install DDEV
        run: |
          curl -fsSL https://ddev.com/install.sh | bash
          if [ "${{ matrix.ddev_version }}" = "HEAD" ]; then
            sudo apt-get update && sudo apt-get install -y build-essential
            git clone https://github.com/ddev/ddev.git
            cd ddev
            make
            sudo cp .gotmp/bin/linux_amd64/ddev /usr/local/bin/
          fi
      - name: Install BATS
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
      - name: Run tests
        run: bats tests/test.bats
